---
title: "SelfDescrimination"
output: html_document
date: "2023-11-03"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


### libraries

```{r results = "hold"}
tellme <- function(name){print(paste0("Package ", name, " version: ", packageVersion(name)))}

library(tidyr); tellme("tidyr")
suppressPackageStartupMessages(library(dplyr)); tellme("dplyr")
library(ggplot2); tellme("ggplot2")
library(ggrepel); tellme("ggrepel")
# library(ggrepel); tellme("phyloseq")
# library(ggpubr); tellme("ggpubr")
```

Read the functions made for this approach.
```{r}
source("selfFinderScore_functions.R")
```


## counts

```{r}
# rawcounts <- read.delim2("asv-counts.txt", row.names = 1)
# rawcounts = rawcounts[rowSums(rawcounts) > 0,]
DADA2_part2 = dir("../..", pattern="DADA2_part2", full.names = T, include.dirs = T)
countsFile = file.path(DADA2_part2, "output", "asv-counts.txt")
rawcounts = read.delim2(countsFile, row.names = 1)
rawcounts = rawcounts[rowSums(rawcounts) > 0,]
dim(rawcounts)
```

Normalize counts.
```{r}
counts = lognorm(rawcounts)

relAbund = rawcounts/rowSums(rawcounts)
```


## Pairs

```{r}
# pairs=read.delim("../pairs/pairs_Patient-Nose.txt")
# row.names(pairs) = pairs[,1]

pairSets = dir("../pairs", pattern=".txt", full.names = T)
names(pairSets) = gsub(x=basename(pairSets), pattern=".txt", replacement = "")
pairList = lapply(pairSets, FUN=function(file){
  df = read.delim(file)
  row.names(df) = df[,1]
  df
})
pairs = pairList[["pairs_Patient-Nose"]]
```


## Example with explainations

```{r}
vals = selfSelectionScore(pairs, counts)
```










## Patient examples

```{r}
lognormResults = selfSelectionScore(pairList[["pairs_Patient-Nose"]], 
               counts, title="Patient-Nose, lognorm")
relbundResults = selfSelectionScore(pairList[["pairs_Patient-Nose"]], 
               relAbund, title="Patient-Nose, relAbund")
```


```{r}
rawResults = selfSelectionScore(pairList[["pairs_Patient-Nose"]], 
               rawcounts, title="Patient-Nose, raw", showPlots = F)
show(rawResults$heatmap)
```

Oh... I guess the "raw" counts were actually already scaled (relative abundance).

```{r}
plot(lognormResults$table$score, 
     relbundResults$table$score)
abline(a=0, b=1)

tt = t.test(lognormResults$table$score, relbundResults$table$score, paired = T)

ggplot(data=rbind(data.frame(normalization="lognorm",
                  score=lognormResults$table$score),
                  data.frame(normalization="relAbund",
                             score=relbundResults$table$score)
       ), aes(x=normalization, y=score)) +
  geom_boxplot(outlier.alpha = 0) +
  geom_jitter(width = .2, height = 0) +
  annotate("text", x=1.5, y=.5, label=signif(tt$p.value, 3))
```


```{r}
lognormResults2 = selfSelectionScore(pairList[["pairs_Patient-Axilla"]], 
               counts, title="Patient-Axilla, lognorm")
relbundResults2 = selfSelectionScore(pairList[["pairs_Patient-Axilla"]], 
               relAbund, title="Patient-Axilla, relAbund")

# plot(lognormResults2$table$score, 
#      relbundResults2$table$score)
# abline(a=0, b=1)

tt = t.test(lognormResults2$table$score, relbundResults2$table$score, paired = T)

ggplot(data=rbind(data.frame(normalization="lognorm",
                  score=lognormResults2$table$score),
                  data.frame(normalization="relAbund",
                             score=relbundResults2$table$score)
       ), aes(x=normalization, y=score)) +
  geom_boxplot(outlier.alpha = 0) +
  geom_jitter(width = .2, height = 0) +
  annotate("text", x=1.5, y=.5, label=signif(tt$p.value, 3))
```


```{r}
lognormResults3 = selfSelectionScore(pairList[["pairs_Patient-Hand"]], 
               counts, title="Patient-Hand, lognorm")
relbundResults3 = selfSelectionScore(pairList[["pairs_Patient-Hand"]], 
               relAbund, title="Patient-Hand, relAbund")

plot(lognormResults3$table$score, 
     relbundResults3$table$score)
abline(a=0, b=1)

tt = t.test(lognormResults3$table$score, relbundResults3$table$score, paired = T)

ggplot(data=rbind(data.frame(normalization="lognorm",
                  score=lognormResults3$table$score),
                  data.frame(normalization="relAbund",
                             score=relbundResults3$table$score)
       ), aes(x=normalization, y=score)) +
  geom_boxplot(outlier.alpha = 0) +
  geom_jitter(width = .2, height = 0) +
  annotate("text", x=1.5, y=.5, label=signif(tt$p.value, 3))
```

```{r}
lognormResults3 = selfSelectionScore(pairList[["pairs_Staff-Hand"]], 
               counts, title="Staff-Hand, lognorm")
relbundResults3 = selfSelectionScore(pairList[["pairs_Staff-Hand"]], 
               relAbund, title="Staff-Hand, relAbund")
```

## Staff samples are poo pairs

```{r}
lognormResults3 = selfSelectionScore(pairList[["pairs_Staff-Nose"]], 
               counts, title="Staff-Nose, lognorm")
relbundResults3 = selfSelectionScore(pairList[["pairs_Staff-Nose"]], 
               relAbund, title="Staff-Nose, relAbund")
```


